version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Mount persistent storage for data
      - /mnt/app-data:/app/data
    environment:
      - NODE_ENV=production
      - DATA_PATH=/app/data
    restart: unless-stopped

# On DigitalOcean:
# 1. Create a Volume in the dashboard
# 2. Mount it to /mnt/app-data on your droplet
# 3. Your data persists across deployments!